### ISSUE TITLE
Add a `.py` implementation of `Counting Sort`.

### ISSUE THREAD

**Issue by Ashrockzzz2003** [Ashrockzzz2003/Data_Structures_and_Algorithms#11]
- [ ] Add `sorting/count_sort/count_sort.py`.

Idea from #8. Reserved for @Leela0o5

**Comment by Leela0o5** [comment]
hey @Ashrockzzz2003 
thank you

**Comment by Ashrockzzz2003** [comment]
You have time until `Jan 2, 2025` to raise a PR for this issue.
Thanks for taking it up!
