### ISSUE TITLE
Add a `.cpp` implementation for `Tim Sort`.

### ISSUE THREAD

**Issue by Ashrockzzz2003** [Ashrockzzz2003/Data_Structures_and_Algorithms#16]
- [ ] Add a `.cpp` implementation for `Tim Sort`.
- [ ] Create folder for the same under `sorting`.

Idea from https://github.com/Ashrockzzz2003/Data_Structures_and_Algorithms/issues/8. Reserved for @adofm

**Comment by Praveen20cent** [comment]
I've completed my course in DSA, I think I'd be a good fit for the issue. @Ashrockzzz2003

**Comment by Ashrockzzz2003** [comment]
@Praveen20cent. This was requested by @adofm already. 
Sorry, please find a different issue!

**Comment by adofm** [comment]
Hi will get this done.

**Comment by Ashrockzzz2003** [comment]
You've time until `Jan 2, 2025` to raise a PR>
