### ISSUE TITLE
Move implementations of `Dijkstra` and `Bellmann Ford` to respective directories

### ISSUE THREAD

**Issue by Ashrockzzz2003** [Ashrockzzz2003/Data_Structures_and_Algorithms#17]
The implementations [already exist in a different file](https://github.com/Ashrockzzz2003/Data_Structures_and_Algorithms/blob/main/non_linear/graphs/text_book_based/shortest_paths/shortest_paths.py). 

- [ ] Split them up and put em inside the created folders.

Idea from #8. Reserved for @akshayks13

**Comment by Praveen20cent** [comment]
I've completed my course in DSA, I think I'd be a great fit for the issue. @Ashrockzzz2003

**Comment by Ashrockzzz2003** [comment]
Again @Praveen20cent 
Sorry!!
please check description
It was requested by @akshayks already in #8

**Comment by Praveen20cent** [comment]
Okay...Hope I reserve something new first 😄

**Comment by Ashrockzzz2003** [comment]
You can request for ideas in #8

**Comment by akshayks13** [comment]
> Again @Praveen20cent 
> 
> Sorry!!
> 
> please check description
> 
> It was requested by @akshayks13 already in #8

Hey thanks for saving this issue to me

Would love to work on it

**Comment by adithya-menon-r** [comment]
Hey @Ashrockzzz2003, I would like to solve this issue if there is no progress.

**Comment by Ashrockzzz2003** [comment]
A PR has been raised for the same @adithya-menon-r

**Comment by adithya-menon-r** [comment]
@Ashrockzzz2003 Ah sorry... Didn't see it
