### ISSUE TITLE
Add documentation on guidelines to contribute.

### ISSUE THREAD

**Issue by Ashrockzzz2003** [Ashrockzzz2003/Data_Structures_and_Algorithms#3]
- [ ] Add documentation on guidelines to contribute.
- [ ] Create `CONTRIBUTING.md`.
- [ ] Create `CODE_OF_CONDUCT.md`
- [ ] Create `SECURITY.md`.
- [ ] Make sure all of them are in `/docs` folder.

**Comment by Keerthivasan-Venkitajalam** [comment]
I'd like to handle this issue please @Ashrockzzz2003

**Comment by Ashrockzzz2003** [comment]
Hey @Keerthivasan-Venkitajalam 
Thanks for taking it up. Assigning this to you.
You have time until `Jan 2, 2025` to come up with a PR.

**Comment by Keerthivasan-Venkitajalam** [comment]
PR done for the Issue...
@Ashrockzzz2003 Please review the changes and share your feedback and modifications if any. 😊

**Comment by VishalTheHuman** [comment]
@Keerthivasan-Venkitajalam Try styling it better with markdown features and make it more readable. take your time.

**Comment by Keerthivasan-Venkitajalam** [comment]
> @Keerthivasan-Venkitajalam Try styling it better with markdown features and make it more readable. take your time.

Sure @VishalTheHuman... Will do that, Thank you :)
