### ISSUE TITLE
Add a `.go` implementation of Skip Lists

### ISSUE THREAD

**Issue by IAmRiteshKoushik** [Ashrockzzz2003/Data_Structures_and_Algorithms#30]

**Comment by FLASH2332** [comment]
I am interested in doing this @IAmRiteshKoushik

**Comment by Ashrockzzz2003** [comment]
Assigned @FLASH2332

**Comment by FLASH2332** [comment]
I'm considering implementing skip lists with insert, delete, search, and display methods. I'll use the coin toss method to determine the number of levels. 

The coin toss method is a classic and elegant way to maintain the balance in skip lists, ensuring that the levels are distributed probabilistically, which helps in achieving the desired time complexity.

Will that be good?
