### ISSUE TITLE
Remove `.DS_Store` files from the repo and add it to `.gitignore`.

### ISSUE THREAD

**Issue by Ashrockzzz2003** [Ashrockzzz2003/Data_Structures_and_Algorithms#4]
- [ ] Remove `.DS_Store` files from the repo.
- [ ] Add it to `.gitignore`.

This issue is meant explicitly for `1st years` participating in WOC.

**Comment by BIJJUDAMA** [comment]
I am interested in doing this task. Please assign it to me @Ashrockzzz2003

**Comment by Ashrockzzz2003** [comment]
Hey @BIJJUDAMA 
Thanks for taking it up. Assigned to you.

**Comment by BIJJUDAMA** [comment]
PR has been done for the issue @Ashrockzzz2003 
Please review :)
