### ISSUE TITLE
Add .py implementation of Doubly Linked Circular List, Queue, Stack, Deque

### ISSUE THREAD

**Issue by rev-sin** [Ashrockzzz2003/Data_Structures_and_Algorithms#48]
Would like to open PR once tags and bounties are assigned. Thanks in advance.

@Ashrockzzz2003 @mdxaasil @FirefoxSRV

**Comment by Ashrockzzz2003** [comment]
@rev-sin 
This is absolutely ridiculous!
Bad practice. You can't just spam a repository if we don't reply to an issue. You just created 5 copies of the same issue.

Please refrain from such things

And
The implementations already exist @rev-sin https://github.com/Ashrockzzz2003/Data_Structures_and_Algorithms/tree/main/linear

So closing it.

**Comment by Ashrockzzz2003** [comment]
![image](https://github.com/user-attachments/assets/68db1bd2-e427-4739-b8dd-99cb00387ba6)

Absolutely ridiculous! This is a warning. If more such incidents are seen, you'll be barred from the WOC competition.
