### ISSUE TITLE
Add a `.cpp` implementation for `Quick Sort` algorithm.

### ISSUE THREAD

**Issue by Ashrockzzz2003** [Ashrockzzz2003/Data_Structures_and_Algorithms#6]
- [ ] Add a `.cpp` implementation for `Quick Sort` algorithm.

**Comment by hirux06** [comment]
Since I've completed my course in DSA, I think I'd be a great fit for the issue. @Ashrockzzz2003

**Comment by Ashrockzzz2003** [comment]
Hey @hirux06 
Thanks for taking it up
Assigning this to you.


You have time until `December 31, 2025` to finish this.

**Comment by hirux06** [comment]
Issue solved in #10
