### ISSUE TITLE
Add a `.go` implementation of `Huffmann` compression algorithm.

### ISSUE THREAD

**Issue by Ashrockzzz2003** [Ashrockzzz2003/Data_Structures_and_Algorithms#7]
- [ ] Add a `.go` implementation of `Huffmann` compression algorithm.

**Comment by FLASH2332** [comment]
I would like to work on this issue @Ashrockzzz2003

**Comment by Ashrockzzz2003** [comment]
Thanks you @FLASH2332 (CB.SC.U4CSE23030) for taking it up. Assigned to you. You've time till `Jan 2, 2025` to come up with a PR.

**Comment by FLASH2332** [comment]
I've started a PR for my current issue. I'm also ready to implement the Go version of sorting algorithms—can I take it up next?
